spring.application.name=notes-app

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=${PORT:8080}

# JWT Configuration
jwt.secret=${JWT_SECRET_KEY:mySecretKey123456789012345678901234567890}
jwt.expiration=86400000
